# Generated by Django 2.1.5 on 2019-02-04 15:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wiki', '0003_auto_20190129_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
