# Generated by Django 2.1.5 on 2019-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_urlpath_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpath',
            name='npb_file',
            field=models.FileField(blank=True, null=True, upload_to='npb'),
        ),
    ]
